name: CI

on:
  push:
    branches:
      - master
      - stage
      - prod
  pull_request:
    branches: 
      - master
      - stage
      - prod

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify is for all pushes / PRs
        run: echo Verify job running...
      - name: Dump Github info
        run: echo ${{ toJSON(github) }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Build job running...
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/prod'
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Deploy job running...
