name: CI

on:
  push:
    branches:
      - master
      - stage
      - prod
  pull_request:
    branches: 
      - master
      - stage
      - prod

jobs:
  build:
    name: Verify + Build 
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/stage' && github.ref != 'refs/heads/prod'
    steps:
      - name: Verify + Build is for all PRs to master/stage/prod.
        run: echo build job running...
  deploy:
    name: Verify + Build + Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/prod'
    steps:
      - name: Verify + Build + Deploy is for all pushes to master/stage/prod.
        run: echo Deploy job running...
